### ISSUE TITLE
Error while executing script

### ISSUE THREAD

**Issue by matteotoma98** [AndreiV03/instagram-unfollowers#3]
VM182:1 Something went wrong!
TypeError: Cannot read properties of undefined (reading 'user')

**Comment by andreiv03** [comment]
Where do you get this error?

**Comment by matteotoma98** [comment]
On chrome after press enter (after pasted your script)

**Comment by andreiv03** [comment]
You must be logged in to instagram.com
Does this issue occur on the Instagram website even when you're signed in?

**Comment by matteotoma98** [comment]
Yes, even if i signed in.

**Comment by andreiv03** [comment]
Can you send me a screenshot from your browser? It would help me a lot. Thank you for your time!

**Comment by matteotoma98** [comment]
![image](https://user-images.githubusercontent.com/48352371/186999628-331ba596-ba13-46e3-808f-0617118a29d5.png)
Chrome version:
Version 104.0.5112.102 (Official Build) (64-bit)
Thanks u too.

**Comment by andreiv03** [comment]
You're getting an HTTP 429 error, which means that you've had too many requests, so your IP address was been temporarily banned from fetching that URL. I'll try to increase the waiting time in order to avoid this problem. Thanks!
